import sys
sys.stdout.reconfigure(encoding='utf-8', errors='replace')

fp = 'X:/Qoder proyects/PadelRush/src/pages/Express.jsx'
with open(fp, 'r', encoding='utf-8') as f:
    c = f.read()

before = c[:22066]
after = c[30570:]

lines = []
L = lines.append

L('        <Tabs value={activeRound} onValueChange={setActiveRound} className="w-full">')
L('          <div className="-mx-4 sm:mx-0">')
L('            <TabsList className="w-full justify-start overflow-x-auto scrollbar-hide px-4 sm:px-0 gap-0.5">')
L('              {rounds.map((round, ri) => {')
L('                const roundPlayed = round.matches.every(m => m.played)')
L('                return (')
L('                  <TabsTrigger')
L('                    key={ri}')
L('                    value={String(ri)}')
L('                    className="gap-1.5 text-xs sm:text-sm px-2.5 sm:px-3 py-1.5 sm:py-2 min-h-[36px]">')
L('                    <span className="flex items-center gap-1.5">')
L('                      R{round.number}')
L('                      {roundPlayed && <CheckCircle2 className="w-3 h-3 text-primary shrink-0" />}')
L('                    </span>')
L('                  </TabsTrigger>')
L('                )')
L('              })')
L('            </TabsList>')
L('          </div>')
L('          {rounds.map((round, ri) => (')
L('            <TabsContent key={ri} value={String(ri)} className="mt-0">')
L('              <motion.div')
L('                initial={{ opacity: 0, y: 8 }}')
L('                animate={{ opacity: 1, y: 0 }}')
L("                transition={{ duration: 0.25, ease: 'easeOut' }}")
L('                className="grid grid-cols-1 sm:grid-cols-2 gap-3 sm:gap-4"')
L('              >')
L('                {round.matches.map((match, mi) => {')
L('                  const isAWinner = match.played && match.winner === 1')
L('                  const isBWinner = match.played && match.winner === 2')
L('                  const hasScore = (match.score?.a ?? 0) > 0 || (match.score?.b ?? 0) > 0')
L('                  const isLive = hasScore && !match.played')
L('                  return (')
L('                    <div')
L('                      key={match.id}')
L('                      className={cn(')
L("                        'bg-card border transition-all duration-200 overflow-hidden',")
L("                        match.played ? 'border-border' : 'border-border/60 hover:border-foreground/30'")
L('                      )}')
L('                    >')
L('                      {/* --- Court header --- */}')
L('                      <div className={cn(')
L("                        'flex items-center justify-between px-3 sm:px-4 py-2 border-b',")
L("                        match.played ? 'bg-muted/20 border-border' : 'bg-muted/10 border-border/60'")
L('                      )}>')
L('                        <div className="flex items-center gap-2">')
L('                          <div className={cn(')
L("                            'w-6 h-6 sm:w-7 sm:h-7 flex items-center justify-center rounded-full text-[10px] sm:text-xs font-bold',")
L("                            match.played ? 'bg-foreground text-background' : 'bg-muted-foreground/20 text-muted-foreground'")
L('                          )}>{match.court}</div>')
L('                          <span className="text-xs sm:text-sm font-semibold text-foreground">Cancha {match.court}</span>')
L('                        </div>')
L('                        <div className="flex items-center gap-1.5">')
L('                          {isLive && <span className="w-1.5 h-1.5 rounded-full bg-green-500 animate-pulse" />}')
L('                          <span className={cn(')
L("                            'text-[10px] sm:text-xs font-medium px-2 py-0.5 rounded-full',")
L("                            match.played ? 'bg-primary/10 text-primary' : isLive ? 'bg-green-500/10 text-green-600' : 'bg-muted-foreground/10 text-muted-foreground'")
L('                          )}>{match.played ? 'Jugado' : isLive ? 'En vivo' : 'Pendiente'}</span>')
L('                        </div>')
L('                      </div>')
L('')
L('                      {/* --- Team A --- */}')
L('                      <div className="p-3 sm:p-4 space-y-0">')
L('                        <div className={cn(')
L("                          'flex items-center gap-3 sm:gap-4 px-3 sm:px-4 py-2.5 sm:py-3 rounded-lg transition-colors',")
L("                          isAWinner ? 'bg-primary/5 ring-1 ring-primary/20' : (match.played ? 'bg-muted/20' : 'hover:bg-muted/30')")
L('                        )}>')
L('                          <div className="flex items-center justify-center w-6 h-6 sm:w-7 sm:h-7">')
L('                            {isAWinner && <Trophy className="w-3.5 h-3.5 sm:w-4 sm:h-4 text-primary" />}')
L('                          </div>')
L('                          <div className="flex-1 min-w-0">')
L("                            <div className={cn('text-sm sm:text-base font-bold truncate', isAWinner ? 'text-primary' : 'text-foreground')}>{match.pairA[0].name}</div>")
L("                            <div className={cn('text-xs sm:text-sm truncate', isAWinner ? 'text-primary/70' : 'text-muted-foreground')}>{match.pairA[1].name}</div>")
L('                          </div>')
L('                          <div className={cn('w-10 h-10 sm:w-12 sm:h-12 rounded-lg overflow-hidden shrink-0', isAWinner ? 'ring-2 ring-primary' : 'ring-1 ring-border')}>')
L('                            <ScoreCell value={match.score?.a ?? 0} onChange={(v) => handleSaveScore(ri, mi, v, match.score?.b ?? 0)} isWinner={isAWinner} />')
L('                          </div>')
L('                        </div>')
L('')
L('                        {/* VS divider */}')
L('                        <div className="flex items-center gap-2 sm:gap-3 px-3 sm:px-4 py-1">')
L('                          <div className="flex-1 h-px bg-border/50" />')
L('                          <span className="text-[10px] sm:text-xs font-bold text-muted-foreground/40 uppercase tracking-widest">VS</span>')
L('                          <div className="flex-1 h-px bg-border/50" />')
L('                        </div>')
L('')
L('                        {/* Team B */}')
L('                        <div className={cn(')
L("                          'flex items-center gap-3 sm:gap-4 px-3 sm:px-4 py-2.5 sm:py-3 rounded-lg transition-colors',")
L("                          isBWinner ? 'bg-primary/5 ring-1 ring-primary/20' : (match.played ? 'bg-muted/20' : 'hover:bg-muted/30')")
L('                        )}>')
L('                          <div className="flex items-center justify-center w-6 h-6 sm:w-7 sm:h-7">')
L('                            {isBWinner && <Trophy className="w-3.5 h-3.5 sm:w-4 sm:h-4 text-primary" />}')
L('                          </div>')
L('                          <div className="flex-1 min-w-0">')
L("                            <div className={cn('text-sm sm:text-base font-bold truncate', isBWinner ? 'text-primary' : 'text-foreground')}>{match.pairB[0].name}</div>")
L("                            <div className={cn('text-xs sm:text-sm truncate', isBWinner ? 'text-primary/70' : 'text-muted-foreground')}>{match.pairB[1].name}</div>")
L('                          </div>')
L('                          <div className={cn('w-10 h-10 sm:w-12 sm:h-12 rounded-lg overflow-hidden shrink-0', isBWinner ? 'ring-2 ring-primary' : 'ring-1 ring-border')}>')
L('                            <ScoreCell value={match.score?.b ?? 0} onChange={(v) => handleSaveScore(ri, mi, match.score?.a ?? 0, v)} isWinner={isBWinner} />')
L('                          </div>')
L('                        </div>')
L('')
L('                        {/* Winner result line */}')
L('                        {match.played ? (')
L('                          <div className="mt-2 px-3 sm:px-4">')
L('                            <div className={cn(')
L("                              'text-[10px] sm:text-xs font-semibold text-center py-1.5 rounded-md',")
L("                              match.winner ? 'bg-primary/5 text-primary' : 'bg-muted text-muted-foreground'")
L('                            )}>')
L('          
