/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: { DEFAULT: 'hsl(var(--primary))', foreground: 'hsl(var(--primary-foreground))', light: 'hsl(var(--primary-light))', dark: 'hsl(var(--primary-dark))' },
        secondary: { DEFAULT: 'hsl(var(--secondary))', foreground: 'hsl(var(--secondary-foreground))' },
        destructive: { DEFAULT: 'hsl(var(--destructive))', foreground: 'hsl(var(--destructive-foreground))' },
        muted: { DEFAULT: 'hsl(var(--muted))', foreground: 'hsl(var(--muted-foreground))' },
        accent: { DEFAULT: 'hsl(var(--accent))', foreground: 'hsl(var(--accent-foreground))' },
        popover: { DEFAULT: 'hsl(var(--popover))', foreground: 'hsl(var(--popover-foreground))' },
        card: { DEFAULT: 'hsl(var(--card))', foreground: 'hsl(var(--card-foreground))' },
        success: { DEFAULT: 'hsl(var(--success))', foreground: 'hsl(var(--success-foreground))' },
        warning: { DEFAULT: 'hsl(var(--warning))', foreground: 'hsl(var(--warning-foreground))' },
        sidebar: {
          DEFAULT: 'hsl(var(--sidebar))',
          foreground: 'hsl(var(--sidebar-foreground))',
          accent: 'hsl(var(--sidebar-accent))',
          muted: 'hsl(var(--sidebar-muted))',
          border: 'hsl(var(--sidebar-border))',
        },
        'level-3ra': 'rgb(var(--level-3ra) / <alpha-value>)',
        'level-3ra-bg': 'rgb(var(--level-3ra-bg) / <alpha-value>)',
        'level-3ra-border': 'rgb(var(--level-3ra-border) / <alpha-value>)',
        'level-4ta': 'rgb(var(--level-4ta) / <alpha-value>)',
        'level-4ta-bg': 'rgb(var(--level-4ta-bg) / <alpha-value>)',
        'level-4ta-border': 'rgb(var(--level-4ta-border) / <alpha-value>)',
        'level-5ta': 'rgb(var(--level-5ta) / <alpha-value>)',
        'level-5ta-bg': 'rgb(var(--level-5ta-bg) / <alpha-value>)',
        'level-5ta-border': 'rgb(var(--level-5ta-border) / <alpha-value>)',
        'level-6ta': 'rgb(var(--level-6ta) / <alpha-value>)',
        'level-6ta-bg': 'rgb(var(--level-6ta-bg) / <alpha-value>)',
        'level-6ta-border': 'rgb(var(--level-6ta-border) / <alpha-value>)',
        'chart-grid': 'rgb(var(--chart-grid) / <alpha-value>)',
        'chart-tick': 'rgb(var(--chart-tick) / <alpha-value>)',
        'medal-gold': 'rgb(var(--medal-gold) / <alpha-value>)',
        'medal-silver': 'rgb(var(--medal-silver) / <alpha-value>)',
        'medal-bronze': 'rgb(var(--medal-bronze) / <alpha-value>)',
      },
      fontFamily: {
        sans: ['Geist', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'monospace'],
        heading: ['Geist', 'system-ui', 'sans-serif'],
        body: ['Geist', 'system-ui', '-apple-system', 'sans-serif'],
        score: ['JetBrains Mono', 'monospace'],
      },
      borderRadius: {
        DEFAULT: '0.5rem',
      },
      transitionDuration: {
        '250': '250ms',
        '400': '400ms',
      },
      transitionTimingFunction: {
        'smooth': 'cubic-bezier(0.4, 0, 0.2, 1)',
      },
      boxShadow: {
        'border': 'var(--shadow-border)',
        'card': 'var(--shadow-card)',
        'card-hover': 'var(--shadow-card-hover)',
        'elevated': 'var(--shadow-elevated)',
        'focus': 'var(--shadow-focus)',
        'glow-sm': 'var(--shadow-glow-sm)',
      },
      keyframes: {
        shimmer: {
          '0%': { backgroundPosition: '200% 0' },
          '100%': { backgroundPosition: '-200% 0' },
        },
      },
      animation: {
        shimmer: 'shimmer 2s ease-in-out infinite',
      },
      screens: {
        'xs': '475px',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
}
